"""added timestamp for lecture time

Revision ID: 0d16bae7fa8d
Revises: 5aef9a09db86
Create Date: 2021-09-24 10:09:42.002685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d16bae7fa8d'
down_revision = '5aef9a09db86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
