"""empty message

Revision ID: 21e6e6ec8953
Revises: 9c12e8b2707d
Create Date: 2021-09-24 14:07:54.411184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21e6e6ec8953'
down_revision = '9c12e8b2707d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('sede', sa.String(), nullable=True),
    sa.Column('aula', sa.String(), nullable=True),
    sa.Column('data_lezione', sa.String(), nullable=True),
    sa.Column('ora_inizio', sa.String(), nullable=True),
    sa.Column('ora_fine', sa.String(), nullable=True),
    sa.Column('qr', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ora_inizio_lezione', sa.String(), nullable=True),
    sa.Column('ora_fine_lezione', sa.String(), nullable=True),
    sa.Column('lecture_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.drop_table('Lectures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lectures',
    sa.Column('entry_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Lectures_entry_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('sede', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aula', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_lezione', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ora_inizio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ora_fine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ora_inizio_lezione', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ora_fine_lezione', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lecture_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('entry_id', name='Lectures_pkey')
    )
    op.drop_table('lectures')
    # ### end Alembic commands ###
