"""added timestamp for lecture time

Revision ID: 5aef9a09db86
Revises: 588052299d39
Create Date: 2021-09-24 10:04:54.218906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aef9a09db86'
down_revision = '588052299d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lectures', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lectures', 'created_at')
    # ### end Alembic commands ###
