"""added timestamp for lecture time

Revision ID: 650496c9b4f5
Revises: 688a3a7ff418
Create Date: 2021-09-24 09:56:57.701752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650496c9b4f5'
down_revision = '688a3a7ff418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
