"""empty message

Revision ID: 9c12e8b2707d
Revises: 
Create Date: 2021-09-24 11:15:17.947241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c12e8b2707d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lectures',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('sede', sa.String(), nullable=True),
    sa.Column('aula', sa.String(), nullable=True),
    sa.Column('data_lezione', sa.String(), nullable=True),
    sa.Column('ora_inizio', sa.String(), nullable=True),
    sa.Column('ora_fine', sa.String(), nullable=True),
    sa.Column('qr', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ora_inizio_lezione', sa.String(), nullable=True),
    sa.Column('ora_fine_lezione', sa.String(), nullable=True),
    sa.Column('lecture_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lectures')
    # ### end Alembic commands ###
