"""added timestamp for lecture time

Revision ID: a43e522d9a0e
Revises: 0d16bae7fa8d
Create Date: 2021-09-24 10:18:41.328433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a43e522d9a0e'
down_revision = '0d16bae7fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lectures', sa.Column('lecture_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('Lectures', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lectures', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Lectures', 'lecture_timestamp')
    # ### end Alembic commands ###
